const express = require('express')
const router = express.Router()

const authRouter = require('./authRouter')
const staffAuthRouter = require('./staffAuthRouter')
const materialRouter = require('./materialRouter')
const recipeRouter = require('./recipeRouter')
const supplierRouter = require('./supplierRouter')
const branchRouter = require('./branchRouter')
const importRequestRouter = require('./importRequestRouter')
const orderRouter = require('./orderRouter')
const customerRouter = require('./customerRouter')
const emailRouter = require('./emailRouter')
const cakeRouter = require('./cakeRouter')
const categoryRouter = require('./categoryRouter')
const cartRouter = require('./cartRouter')
const voucherRouter = require('./voucherRouter')
const staffRouter = require('./staffRouter')
const planRouter = require('./planRouter')
const vnpayRouter = require('./vnpayRouter')
const analyticsRouter = require('./analyticsRouter')

router.use('/auth', authRouter)
router.use('/staff-auth', staffAuthRouter)
router.use('/staffs', staffRouter)
router.use('/materials', materialRouter)
router.use('/recipes', recipeRouter)
router.use('/suppliers', supplierRouter)
router.use('/plans', planRouter)
router.use('/branches', branchRouter)
router.use('/import-requests', importRequestRouter)
router.use('/orders', orderRouter)
router.use('/customers', customerRouter)
router.use('/email', emailRouter)
router.use('/cakes', cakeRouter)
router.use('/categories', categoryRouter)
router.use('/carts', cartRouter)
router.use('/vouchers', voucherRouter)
router.use('/vnpay', vnpayRouter)
router.use("/analytics", analyticsRouter)

module.exports = router
